spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Seoul

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.dopamin.omok: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
